In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv('archivos_semana_4/usuarios_win_mac_lin.csv')

# Verificamos la estructura (clases: 0-Win, 1-Mac, 2-Lin)
print(df.groupby('clase').size())
df.head()

# Visualizamos la relación entre duración y cantidad de acciones por clase
sns.pairplot(df, hue='clase', vars=['duracion', 'paginas', 'acciones', 'valor'], palette='viridis')
plt.show()

clase
0    86
1    40
2    44
dtype: int64


,duracion,paginas,acciones,valor,clase
0,7.0,2,4,8,2
1,21.0,2,6,6,2
2,57.0,2,4,4,2
3,101.0,3,6,12,2
4,109.0,2,6,12,2


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv('archivos_semana_4/usuarios_win_mac_lin.csv')

X = df.drop('clase', axis=1) # Todas las columnas menos la etiqueta
y = df['clase']

# División Train/Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creamos el modelo de Regresión Logística
# Aumentamos max_iter si el modelo no converge
modelo_log = LogisticRegression(max_iter=1000)
modelo_log.fit(X_train, y_train)

y_pred = modelo_log.predict(X_test)

# Matriz de Confusión: Para ver dónde se equivoca más el modelo
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

# Reporte de Clasificación: Precisión, Recall y F1-Score
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))

Matriz de Confusión:
[[13  2  1]
 [ 8  4  0]
 [ 0  0  6]]

Reporte de Clasificación:
              precision    recall  f1-score   support

           0       0.62      0.81      0.70        16
           1       0.67      0.33      0.44        12
           2       0.86      1.00      0.92         6

    accuracy                           0.68        34
   macro avg       0.71      0.72      0.69        34
weighted avg       0.68      0.68      0.65        34

