In [14]:
import numpy as np

#Ejercicio 1: Crear un array de 10 elementos con ceros.

ej_1 = np.zeros(10)
print("Ejercicio 1", ej_1)

#Ejercicio 2: Genera un array con los números del 1 al 20.

ej_2 = np.arange(1, 21)
print("Ejercicio 2", ej_2)


#Ejercicio 3: Crea un array con los números pares del 2 al 50.

ej_3 = np.arange(2, 51, 2)
print("Ejercicio 3", ej_3)

#Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.
ej_5 = np.random.rand(4, 4)
print("Ejercicio 5", ej_5)

#Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

a = np.array([1,2,3])
b = np.array([4,5,6])

ej_6 = a + b
print("Ejercicio 6", ej_6)

#Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

m1 = np.random.randint(1, 11, size=(3, 3))
m2 = np.random.randint(1, 11, size=(3, 3))

ej_7 = m1 * m2
print(f"Ejercicio 7: \nMatriz 1: \n{m1} \nMatriz 2: \n{m2} \nMultiplicadas: \n{ej_7}")

#Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

ej_8 = np.random.randint(1, 101, size=15)

maximo = ej_8.max()
minimo = ej_8.min()
promedio = ej_8.mean()

print(f"Ejercicio 8:\n Array: {ej_8} \n Maximo: {maximo}\n Minimo: {minimo}\n Promedio: {promedio}")

#Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

ej_9 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(ej_9)
print(f"Ejercicio 9: \n Matriz:\n {ej_9} \n Diagonal: {diagonal}")

#Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna

ej_10 = np.random.randint(1, 21, size=(5, 5))
suma_fila = ej_10.sum(axis=1)
suma_columnas = ej_10.sum(axis=0)
print(f"Ejercicio 10:\n {ej_10} \n Suma por filas: {suma_fila}\n Suma por columnas: {suma_columnas}")

Ejercicio 1 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ejercicio 2 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Ejercicio 3 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Ejercicio 5 [[0.85738029 0.52133002 0.08803099 0.43532191]
 [0.43627068 0.63696217 0.47155391 0.46110678]
 [0.07226042 0.0699821  0.60738781 0.85240739]
 [0.19881564 0.88359847 0.08445904 0.33356964]]
Ejercicio 6 [5 7 9]
Ejercicio 7: 
Matriz 1: 
[[3 6 6]
 [2 4 9]
 [6 2 3]] 
Matriz 2: 
[[8 4 4]
 [9 4 4]
 [3 4 2]] 
Multiplicadas: 
[[24 24 24]
 [18 16 36]
 [18  8  6]]
Ejercicio 8:
 Array: [12 14 57 81 52 46 45 47 56 75 30  1 57 70 93] 
 Maximo: 93
 Minimo: 1
 Promedio: 49.06666666666667
Ejercicio 9: 
 Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 
 Diagonal: [ 1  7 13 19 25]
Ejercicio 10:
 [[15 16 15  8  9]
 [ 2 18 15 19 13]
 [ 7  7  2  5 19]
 [ 2 17 10  3 17]
 [15 14  7 14  6]] 
 Suma por filas: [63 67 40 49 56]
 Suma por columnas